# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediaPath',
            field=models.CharField(max_length=1000),
        ),
    ]
